project:
  type: website
  output-dir: docs

website:
  favicon: figs/crow_s.png
  title: "Raven's Nest"
  image: figs/preview.png
  open-graph: true
  description: "Raven's Nest, a personal blog"
  site-url: https://yyraven.github.io/quarto-blog/
  site-path: "/"
  body-footer: |
    <center>Â© 2024-2025 RavensNest.</center>
  page-navigation: true
  bread-crumbs: false
  search:
    location: navbar
  navbar:
    left:
    - text: Work
      href: work.qmd
    - text: Personal
      href: personal.qmd
    - text: Archive
      href: archive.qmd
    right:
    - text: About
      href: about.qmd
    - text: RSS
      href: index.xml

  sidebar:
    - id: personal
      style: "floating"
      border: false
      background: none
      foreground: "#635d5d"
      collapse-level: -1
      contents:
        - text: "All About Birding"
          href: personal/nd_birding/index.qmd
        - section: "Review"
          contents:
            - personal/nd_personal_library/index.qmd
            - auto: "personal/*review*/*.qmd"
        - section: "Radio"
          contents:
            - auto: "personal/*radio*/*.qmd"
        - section: "Diary"
          contents:
            - auto: "personal/*diary*/*.qmd"
    - id: work
      style: "floating"
      border: false
      background: none
      foreground: "#635d5d"
      collapse-level: -1
      contents:
        - section: "Projects"
          contents:
            - auto: "work/*project*/*.qmd"
        - section: "Resources"
          contents:
            - auto: "work/*resources*/*.qmd"

format:
  html:
    grid:
      sidebar-width: 150px
      margin-width: 250px
      body-width: 1000px
    theme:
        - morph
        - focused.scss

callout-appearance: simple
